<?php
/*-------------------------------------------------------+
| Navision API Tools                                     |
| Heinrich Böll Stiftung                                 |
| Copyright (C) 2018 SYSTOPIA                            |
| Author: P. Batroff (batroff@systopia.de)               |
| http://www.systopia.de/                                |
+--------------------------------------------------------+
| This program is released as free software under the    |
| Affero GPL license. You can redistribute it and/or     |
| modify it under the terms of this license which you    |
| can read by viewing the included agpl.txt or online    |
| at www.gnu.org/licenses/agpl.html. Removal of this     |
| copyright header is strictly prohibited without        |
| written permission from the original author(s).        |
+--------------------------------------------------------*/

/**
 * Class CRM_Nav_SOAPDebugClient
 */
class CRM_Nav_SOAPDebugClient extends SoapClient {

  public function __doRequest($request, $location, $action, $version, $one_way = 0) {
    echo "Request:\n" . $request;
    echo "\nLocation:\n" . $location;
    echo "\nAction:\n" . $action;
    echo "\nVersion:\n" . $version;
    echo "\nOneWay: " . $one_way . "\n";
    return parent::__doRequest($request, $location, $action, $version, $one_way); // TODO: Change the autogenerated stub
  }
}

// TODO: maybe overwrite result as well. Parse arguments?